### ISSUE TITLE
seems not working 

### ISSUE THREAD

**Issue by x1angli** [Jamesits/windows-10-font-fallback-reg#2]
hello Jamesits

I am a programmer who prefer to use English as the UI language. Like you said, the font fallback problems bother me. In particular, the default behavior of Windows font fallback is to try English font first, then try the Japanese font, then try Chinese font.

Below is what "calibri" characters are actually rendered in MS Excel .. it ought to be rendered as 雅黑……but now actually is rendered as some kind of Japanese fonts

![image](https://user-images.githubusercontent.com/8603485/109995184-07b02100-7d49-11eb-8c06-fdd1be0cf575.png)

I would appreciate if you can help me with that . thanks.

**Comment by x1angli** [comment]
![image](https://user-images.githubusercontent.com/8603485/109995629-6d9ca880-7d49-11eb-8e46-1ddde0051e73.png)
for comparison , ^^ this is the visual effect of 雅黑 -- true chinese fonts

**Comment by mhtvsSFrpHdE** [comment]
@x1angli  U didn't mention currently running Windows operating system version to us  
so we have to assume you are running 20H2 the latest one

Windows are actively changing its code these years, so an 11 month ago reg patch might not work with you  
I'll find the latest zh-cn image to see if there is any update can be made.

**Comment by x1angli** [comment]
Thanks for your reply and taking care of it.

To answer your reply: yes, you re right. Below is the version of Windows I am running

```
Edition	Windows 10 Pro Education
Version	20H2
OS build	19042.844
```

Additional info: I have another PC that runs an earlier version of Win 10 (but I don't have access to it so unable to give you its ver number, but it's definitely NOT 20H2). That earlier version does not have the problem... 

Thanks in advance for you taking time to look into this.

**Comment by x1angli** [comment]
additional info: 
`10.0.19041` doesn't have such problem

**Comment by mhtvsSFrpHdE** [comment]
@x1angli Used "Microsoft Media Creation Tool" generated Chinese Simplified installation media.  
After install, go to Windows Update and install any possible package,  
then open Microsoft Store, update "中文(简体)本地体验包" to latest.

Reboot and export, I find no difference between master branch and latest exported reg files.

I'll suggest you to try to **DELETE** the entire `SystemLink` folder under `FontLink` folder in regedit.exe,  
then import `zh-cn.reg` **IMMEDIATELY** before reboot or shutdown. Right click on folder name to delete it.  
After import, reboot(not shutdown) to take effect.

I made some minor change on folder struct, you can preview before James merge them

https://github.com/mhtvsSFrpHdE/windows-10-font-fallback-reg/tree/master/en_us_patch/en_us_to_zh_cn

**Comment by mhtvsSFrpHdE** [comment]
@x1angli Here are some sample screenshot take in Windows explorer.  
I guess the reason is when Windows importing reg file, some exist value won't be overridden.

My
![image](https://user-images.githubusercontent.com/10773245/111343009-f60a3a00-86b5-11eb-8e31-f6a641da7336.png)

vs

Image from internet
![image](https://user-images.githubusercontent.com/10773245/111342888-d541e480-86b5-11eb-8890-e7c2af95c722.png)

**Comment by x1angli** [comment]
Thanks a tons for your help

I didn't have the opportunity to test as you suggested, but would definitely keep it in mind. 

I will definitely give it a shot the next time I am provisioning a new Windows system

Closing this issue. Much appreciated!
